### PR TITLE
Further fixes for the ebola model

### LINKED ISSUE #101: Randomise initial exposed/infectious in Erlang compartments in Ebola model
This issue is to flag that the current implementation of the ebola model (see #71) initialises exposed and infectious individuals in the first Erlang sub-compartment, given any $N$ such sub-compartments.

This is fine when the number of initially exposed and infectious is low, but proves more an issue when the number is larger, as a large chunk of individuals is moving through the sub-compartments at exactly the same time.

The proposed solution is to modify the code so that initially infectious and exposed individuals are assigned to their respective Erlang sub-compartments in proportion to the admission probabilities vector.

### LINKED ISSUE #111: Add time-dependence to ebola model
This issue is to request the addition of time-dependence to the ebola model, similar to #93 for ODE models.

### LINKED ISSUE #134: Ebola model should be compatible with interventions
This issue is to request that the ebola model should be compatible with rate interventions as they are currently implemented, and allow for the implementation of common outbreak response measures, such as improving hospitalisations.

This requires reframing the model parameters --- `prop_hospitalised`, `etu_safety`, and `funeral_safety` --- as risk parameters which can be reduced by the intervention (as #109 is on hold).

Renaming scheme:
- `prop_hospitalised` -> `prop_community`
- `etu_safety` -> `etu_risk`
- `funeral_safety` -> `funeral_risk`

This should also be applied in the vignettes, with examples of these interventions.

### PR DESCRIPTION
**Pull request by pratikunterwegs**
This PR contains further fixes to the ebola model:
1. Fixes #101 by randomising assignment of exposed, infectious, and hospitalised into the Erlang subcompartments,
2. Fixes #134 by modifying model structure to invert `prop_hospitalised`, `etu_safety` and `funeral_safety` to parameters representing risk, so that `<rate_intervention>`s can be used to reduce these values without allowing #109,
3. Fixes #111 by allowing time-dependence, along with a vignette section on using time-dependence to simulate vaccination.

### CODE REVIEW

File: R/epidemic_ebola.R [hunk 1]
```diff
@@ -168,7 +181,7 @@ prob_discrete_erlang <- function(shape, rate) {
 #' compartment, which holds both recoveries and deaths.
 #'
 #' We assume that deaths outside of hospital lead to funerals that are
-#' potentially not Ebola-safe, and the `funeral_safety` passed as part of the
+#' potentially not Ebola-safe, and the `funeral_risk` passed as part of the
```
Comment (jamesmbaazam) [inline R/epidemic_ebola.R:184]:
```suggestion
#' potentially unsafe burials, and the `funeral_risk` passed as part of the
```

File: R/epidemic_ebola.R [hunk 2]
```diff
@@ -269,23 +306,33 @@ epidemic_ebola_r <- function(population, infection,
...
+  )
   infectious_past <- infectious_current
 
-  hospitalised_current[n_infectious_boxcars] <- sim_data[1, "hospitalised"]
+  hospitalised_current <- as.vector(
+    stats::rmultinom(1,
+      size = sim_data[1, "hospitalised"],
+      prob = infectious_boxcar_rates
+    )
+  )
```
Comment (jamesmbaazam) [inline R/epidemic_ebola.R:335]: Noting that this is the fix for #101 promised in the PR description. LGTM.

Comment (jamesmbaazam) [reply R/epidemic_ebola.R:335]: Wondering why you're explicitly namespacing the inbuilt functions, i.,e., `rmultinorm()`, `rnorm()`, etc.

File: R/epidemic_ebola.R [hunk 3]
```diff
@@ -294,28 +341,43 @@ epidemic_ebola_r <- function(population, infection,
...
-  parameters <- list(beta = beta)
+  parameters <- list(
+    beta = beta,
+    prop_community = get_parameter(infection, "prop_community"),
+    etu_risk = get_parameter(infection, "etu_risk"),
+    funeral_risk = get_parameter(infection, "funeral_risk")
+  )
 
   ## Run the simulation from time t = 2 to t = time_end
   for (time in seq(2, time_end)) {
```
Comment (jamesmbaazam) [inline R/epidemic_ebola.R:353]: Maybe call `time` something like `tt` to remove the need for the comment below on which "time" you're using in the functional. There's a lot of "time"'s below and could easily be confused.

File: vignettes/ebola_model.Rmd [hunk 4]
```diff
@@ -350,12 +350,330 @@ ggplot(data_scenarios[compartment == "infectious", ]) +
...
 ```
 
 We see that applying an intervention that reduces transmission can be effective in reducing the number of individuals infected over the outbreak.
-This model will soon be able to accommodate interventions that act on other processes, such as hospitalisation and funeral safety, to model the effect of campaigns to tackle these as sources of infections.
+
+## Modelling the roll-out of vaccination
+
+We can also model the rollout of vaccination against EVD, but because this model is structured differently from other models in _epidemics_, vaccination must be modelled differently too.
+
+`epidemic_ebola_r()` does not accept a vaccination regime as a `<vaccination>` object, but we can still model the effect of vaccination as a gradual decrease in the transmission rate $\beta$ over time.
```
Comment (jamesmbaazam) [inline vignettes/ebola_model.Rmd:363]: [Ebola vaccination targets susceptible or at-risk individuals](https://www.who.int/news-room/questions-and-answers/item/ebola-vaccines). So, conceptually, it's better to model it as an increased removal from the susceptible class into the removed class.

File: vignettes/ebola_model.Rmd [hunk 5]
```diff
@@ -350,12 +350,330 @@ ggplot(data_scenarios[compartment == "infectious", ]) +
...
+    xintercept = 15,
+    linetype = "dotted"
+  ) +
+  geom_line(
+    aes(time, value, colour = scenario)
+  ) +
+  scale_colour_brewer(
+    palette = "Set1",
+    name = "Scenario",
+    labels = c("Baseline", "Implementing vaccination")
```
Comment (jamesmbaazam) [inline vignettes/ebola_model.Rmd:421]:
```suggestion
    labels = c("Baseline", "Vaccination campaign")
```

File: vignettes/ebola_model.Rmd [hunk 6]
```diff
@@ -350,12 +350,330 @@ ggplot(data_scenarios[compartment == "infectious", ]) +
...
+
+Similar functionality can be used to affect other model parameters more flexibly than allowed by the `<rate_intervention>` class.
+
+## Modelling a multi-pronged ebola response
+
+Since EVD is a severe disease with a high case fatality risk, responses to an outbreak may require the simultaneous implementation of a number of measures to reduce transmission to end the outbreak quickly.
+
+We can use the EVD model and existing functionality in _epidemics_ to model the implementation of a multi-pronged response to ebola that aims to:
+
+- Improve detection of cases and hospitalise them,
```
Comment (jamesmbaazam) [inline vignettes/ebola_model.Rmd:441]:
```suggestion
- Improve detection and treatment of cases,
```

File: vignettes/ebola_model.Rmd [hunk 7]
```diff
@@ -350,12 +350,330 @@ ggplot(data_scenarios[compartment == "infectious", ]) +
...
+  )
+```
+
+Similar functionality can be used to affect other model parameters more flexibly than allowed by the `<rate_intervention>` class.
+
+## Modelling a multi-pronged ebola response
+
+Since EVD is a severe disease with a high case fatality risk, responses to an outbreak may require the simultaneous implementation of a number of measures to reduce transmission to end the outbreak quickly.
+
+We can use the EVD model and existing functionality in _epidemics_ to model the implementation of a multi-pronged response to ebola that aims to:
```
Comment (jamesmbaazam) [inline vignettes/ebola_model.Rmd:439]:
```suggestion
We can use the EVD model and existing functionality in _epidemics_ to model the implementation of a multi-pronged response to ebola that aims to improve:
```

File: vignettes/ebola_model.Rmd [hunk 8]
```diff
@@ -350,12 +350,330 @@ ggplot(data_scenarios[compartment == "infectious", ]) +
...
+
+- Improve detection of cases and hospitalise them,
+
+- Improve the safety of hospitals and reduce the risk of individuals being treated there passing on ebola to susceptibles in the community, and
```
Comment (jamesmbaazam) [inline vignettes/ebola_model.Rmd:443]:
```suggestion
- safety of hospitals and reduction in the risk of community transmission, and
```

File: vignettes/ebola_model.Rmd [hunk 9]
```diff
@@ -350,12 +350,330 @@ ggplot(data_scenarios[compartment == "infectious", ]) +
...
+
+- Improve the safety of funeral practices to reduce the risk of transmission from individuals who died while infectious with ebola.
```
Comment (jamesmbaazam) [inline vignettes/ebola_model.Rmd:445]:
```suggestion
- safety of funeral practices to reduce the risk of transmission from dead bodies.
```

File: vignettes/ebola_model.Rmd [hunk 10]
```diff
@@ -350,12 +350,330 @@ ggplot(data_scenarios[compartment == "infectious", ]) +
...
+    xintercept = 15,
+    linetype = "dotted"
+  ) +
+  geom_line(
+    aes(time, value, colour = scenario)
+  ) +
+  scale_colour_brewer(
+    palette = "Set1",
+    name = "Scenario",
+    labels = c("Baseline", "Improve hospitalisation")
```
Comment (jamesmbaazam) [inline vignettes/ebola_model.Rmd:496]:
```suggestion
    labels = c("Baseline", "Improved hospitalisation")
```

File: vignettes/ebola_model.Rmd [hunk 11]
```diff
@@ -350,12 +350,330 @@ ggplot(data_scenarios[compartment == "infectious", ]) +
...
+
+### Improving hospitalisation
+
+We first model an intervention that begins 30 days into the outbreak, and reduces the proportion of individuals who are infectious in the community by 30%, thus improving the proportion that are hospitalised.
+
+```{r}
+# create an intervention on the transmission rate
+improve_hospitalisation <- intervention(
+  type = "rate",
+  time_begin = 15, time_end = 100, reduction = 0.3
```
[the remark this answers is not in the document]
Comment (jamesmbaazam) [reply vignettes/ebola_model.Rmd:457]: Although you use `time_begin = 15` throughout so it might make sense to rather change the value in the text to 15 days.

File: R/epidemic_ebola.R [hunk 12]
```diff
@@ -103,10 +110,13 @@ prob_discrete_erlang <- function(shape, rate) {
...
 #' See [intervention()] for details on constructing rate interventions.
-#'
-#' Currently, only interventions on the transmission rate `beta` are supported,
-#' and should be passed as `list(beta = intervention(type = "rate", ...))`.
 #' Defaults to `NULL`, representing no interventions on model parameters.
+#'
+#' @param time_dependence A named list where each name
+#' is a model parameter (see `infection`), and each element is a function with
+#' the first two arguments being the current simulation `time`, and `x`, a value
+#' that is dependent on `time` (`x` represents a model parameter).
```
Comment (jamesmbaazam) [inline R/epidemic_ebola.R:118]: I found this a bit confusing so I'll suggest the following rewording according to how I understand the code.
```suggestion
#' @param time_dependence A named list where each name
#' is a model parameter (see `infection`), and each element is a function with
#' the first two arguments fixed as `time`, and `x`, followed by other arguments to the function. `time` is used internally to refer to the model time at which the parameter value
#' will be changed to `x`.
```

Comment (jamesmbaazam) [reply R/epidemic_ebola.R:118]: Should this allow for multiple breakpoints?

**Review by jamesmbaazam — COMMENTED** [review]
Thanks, @pratikunterwegs. These are nice changes that will introduce some flexibility in the ebola model. I have left line comments. Below, I'm leaving other comments that could not go on lines that were not changed.
 
* In general, the state names vector `c(
    "susceptible", "exposed", "infectious",
    "hospitalised", "funeral", "removed"
  )` is repeated in several places in the code. It would be better to define it once and then use it everywhere.
  
For example, if defined as

`states <- c(
    "susceptible", "exposed", "infectious",
    "hospitalised", "funeral", "removed"
  )`
 
then
* L290 - probably safer to use `length(states)` in case the initial state changes in the future.

* L291 - probably safer to do `colnames(sim_data) <- states`
* Would be nice to have one or two quick examples in the function documentation. You could provide examples with and without time
dependence just to reinforce the idea in the user.

* For the doc of the `time_dependence` argument, please link to
the time_dependence.Rmd vignette.

* In the Ebola vignette, I'm a bit confused about why the scenarios with intervention
tend to have higher outbreak sizes than the baseline as they take off. I would
have expected the opposite.
* More broadly, it would be nice if you could unify the interface by finding a way around applying the `<vaccination>` class to these types of discrete-time models. It would remove any kind of confusion in using time-dependence to model vaccination in Ebola but `<vaccination>` to model vaccination in the other models.

**Comment by pratikunterwegs** [comment]
Thanks @jamesmbaazam for the review, I'll take a look tomorrow and aim to get it merged by the start of next week.

File: R/epidemic_ebola.R (hunk 2 above)
Comment (pratikunterwegs) [reply R/epidemic_ebola.R:335]: Just to be aware where {stats} is being used, since it's being imported.

File: R/epidemic_ebola.R (hunk 3 above)
Comment (pratikunterwegs) [reply R/epidemic_ebola.R:353]: They are all the same `time` - the value used in the functional is intended to be the loop index.

File: vignettes/ebola_model.Rmd (hunk 11 above)
[the remark this answers is not in the document]
Comment (pratikunterwegs) [reply vignettes/ebola_model.Rmd:457]: Thanks yes, the text needs to be changed here so won't add this suggestion to the batch.

File: R/epidemic_ebola.R (hunk 12 above)
Comment (pratikunterwegs) [reply R/epidemic_ebola.R:118]: Not sure what you mean by multiple breakpoints, but it is possible to pass a function that checks the value of time and changes the effect like so. Users can implement multiple cases if they wish, but if they are primarily seeking to model broad, step-wise changes to model parameters they would be better off with a `<rate_intervention>`. The time-dependence functionality works better for modelling small, continuous increments, such as seasonality.

```r
f = function(time, x) ifelse(time < 100, x, x^2)
```

**Comment by pratikunterwegs** [comment]
Thanks @jamesmbaazam,  that was helpful. I've merged most of your suggestions, and taken most of the others too.

> Thanks, [@pratikunterwegs](https://github.com/pratikunterwegs). These are nice changes that will introduce some flexibility in the ebola model. I have left line comments. Below, I'm leaving other comments that could not go on lines that were not changed.

>- In general, the state names vector `c( "susceptible", "exposed", "infectious", "hospitalised", "funeral", "removed" )` is repeated in several places in the code. It would be better to define it once and then use it everywhere.

>For example, if defined as

>`states <- c( "susceptible", "exposed", "infectious", "hospitalised", "funeral", "removed" )`

>then

>- L290 - probably safer to use `length(states)` in case the initial state changes in the future.
    
>- L291 - probably safer to do `colnames(sim_data) <- states`

Thanks, I've defined the compartment names in the function body and reused them for names and lengths
    
>- Would be nice to have one or two quick examples in the function documentation. You could provide examples with and without time  
    dependence just to reinforce the idea in the user.

Broadly agree, however the setup steps for these models are pretty long and are better shown as vignettes to clearly explain setup.
    
>- For the doc of the `time_dependence` argument, please link to  
    the time_dependence.Rmd vignette.

Linked from all instances of this argument.
    
>- In the Ebola vignette, I'm a bit confused about why the scenarios with intervention  tend to have higher outbreak sizes than the baseline as they take off. I would  have expected the opposite.

My guess is that this is an artefact, not a real effect. The interventions mostly take a while to have any effect on the epidemic size.
    
>- More broadly, it would be nice if you could unify the interface by finding a way around applying the `<vaccination>` class to these types of discrete-time models. It would remove any kind of confusion in using time-dependence to model vaccination in Ebola but `<vaccination>` to model vaccination in the other models.

This could be done although it would take some time as the vaccination objects are optimised for the ODE models. More relevant though is that this model doesn't have a vaccinated compartment, as this is not included in Li et al.'s consensus model. We can consider adding one, but my impression is that EVD outbreaks are expected to end before immunity due to vaccination becomes really important.

**Comment by jamesmbaazam** [comment]
> More relevant though is that this model doesn't have a vaccinated compartment, as this is not included in Li et al.'s consensus model. 

That's true. I forgot about that.

>  We can consider adding one, but my impression is that EVD outbreaks are expected to end before immunity due to vaccination becomes really important.

[Reactive ring vaccination is possible](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8659338/). Conceptually, these individuals will not partake in transmission dynamics because they are removed into the absorbing state (here, the removed class) and could contribute to herd immunity.

**Review by jamesmbaazam — APPROVED** [review]

File: R/epidemic_ebola.R [hunk 13]
```diff
@@ -151,15 +161,18 @@ prob_discrete_erlang <- function(shape, rate) {
 #'
 #' ## Hospitalisation, funerals, and removal
 #'
-#' Infectious individuals have a probability of `prop_hospitalised` of being
-#' transferred to the hospitalised compartment.
-#' This compartment has the same number of sub-compartments, which means that
+#' Infectious individuals have a probability of 1.0 - `prop_community` of being
```
[the remark this answers is not in the document]
Comment (jamesmbaazam) [reply R/epidemic_ebola.R:165]: > In this case probability and proportion are interchangeable, no?

I haven't read the paper so I wouldn't know. Also because here, the variable is called `prop_` so why not call it a proportion?

[the remark this answers is not in the document]
Comment (pratikunterwegs) [reply R/epidemic_ebola.R]: Okay thanks. This has been rephrased to being a proportion in https://github.com/epiverse-trace/epidemics/pull/132/commits/0b9a5c62e3986ae40fe2a65dc21c46109c7300ee.
